name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  docker:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_KEY }}

      - name: Set image version
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> "$GITHUB_ENV"
          else
            echo "VERSION=main" >> "$GITHUB_ENV"
          fi

      - name: Build image
        run: IMAGE=debdutdeb/velero-plugin-exclude-with-ownerref VERSION=$VERSION make container

      - name: Push image
        run: IMAGE=debdutdeb/velero-plugin-exclude-with-ownerref VERSION=$VERSION TAG_LATEST=true make push
